amp_kart_bringup: changed server plugins
Autonomous-Motorsports-Purdue/AMP_ASSV3 pull request #14
Opened 2023-02-24 20:37 UTC by jay-jhk-lee

## Brief Description

controller server: default -> regulated pure pursuit
planner server: default -> smac planner

## Details

Increased cost_penalty parameter from default because the kart would collide with obstacles and become stuck; higher cost_penalty results in wider turns around obstacles, but removes that issue.

Fixed issue of paths not being straight when navigating

## Tasks

- [ ] Finished all sub-tasks (from issues)
- [ ] Updated Documentation
- [ ] Tests written/updated and implemented to CI

2023-03-01 03:58 UTC, alanssitis requested changes
@jay-jhk-lee look at the comments I made, just minor changes or clarifying why a change was made.

2023-03-01 03:58 UTC, alanssitis commented on src/amp_kart_bringup/params/nav2.params.yaml
> +    goal_checker_plugins: "goal_checker"
```suggestion
    goal_checker_plugin: "goal_checker"
```
shouldn't be changed

2023-03-01 03:58 UTC, alanssitis commented on src/amp_kart_bringup/params/nav2.params.yaml
> -    use_sim_time: True
shouldn't be removed imo

2023-03-01 03:58 UTC, alanssitis commented on src/amp_kart_bringup/params/nav2.params.yaml
> -    expected_planner_frequency: 20.0
what happens when you add this back?

2023-03-04 20:11 UTC, jay-jhk-lee commented on src/amp_kart_bringup/params/nav2.params.yaml
> -    expected_planner_frequency: 20.0
expected_planner_frequency is a parameter
that sets the lower bound of current current planner frequency
and sends warnings if current goes below expected.
doesn't change the actual functionality of the planner

2023-03-04 22:06 UTC, alanssitis approved these changes
I trust, lgtm

2023-03-04 22:06 UTC, merged