RCS Code
Autonomous-Motorsports-Purdue/AMP_ASSv3 pull request #27
Opened 2023-04-12 20:01 UTC by berliernj

RCS code for communication between track and kart.

2023-04-16 18:18 UTC, alanssitis requested changes

2023-04-16 18:18 UTC, alanssitis commented on src/amp_msgs/package.xml
> +  <test_depend>ament_lint_common</test_depend>
delete these two lines, these are the ones causing the errors

2023-04-16 18:18 UTC, alanssitis commented on src/amp_rcs_client/test/test_flake8.py
delete this file since we already use `yapf` to format

2023-04-16 18:18 UTC, alanssitis commented on src/amp_rcs_client/test/test_copyright.py
not sure if we wanna test this since it could cause errors.

2023-04-16 18:18 UTC, alanssitis commented on src/amp_rcs_client/package.xml
> +  <test_depend>ament_flake8</test_depend>
remove

2023-04-16 18:18 UTC, alanssitis commented on src/amp_rcs_client/package.xml
> +  <test_depend>ament_copyright</test_depend>
look comment below

2023-04-26 18:13 UTC, alanssitis reviewed
I think I found the reason why tests were failing.

Also, create two `README.md`'s and update the main `README.md` to contain info on the new packages.

2023-04-26 18:13 UTC, alanssitis commented on src/amp_rcs_client/setup.cfg
> +script-dir=$base/lib/amp_rcs
```suggestion
script_dir=$base/lib/amp_rcs
```

2023-04-26 18:13 UTC, alanssitis commented on src/amp_rcs_client/setup.cfg
> +install-scripts=$base/lib/amp_rcs
```suggestion
install_scripts=$base/lib/amp_rcs
```

2023-05-10 01:26 UTC, Reschivon approved these changes
Looks good, I assume `NetworkState` is for the ping and should technically belong to that pr but whatever

2023-05-10 15:37 UTC, alanssitis approved these changes

2023-05-10 15:37 UTC, merged