Add Local Goal
Autonomous-Motorsports-Purdue/AMP_ASSv3 pull request #36
Opened 2023-04-27 22:50 UTC by arya1106

## Brief Description

## Related Issues

Closes ...

Opens ...

## Details

## Tasks

2023-04-28 19:54 UTC, alanssitis reviewed
These are package-wide stuff

2023-04-28 19:54 UTC, alanssitis commented on src/amp_local_goal/test/test_copyright.py
delete this file

2023-04-28 19:54 UTC, alanssitis commented on src/amp_local_goal/test/test_flake8.py
delete this file

2023-04-28 19:54 UTC, alanssitis commented on src/amp_local_goal/setup.py
> +    license='TODO: License declaration',
Update these

2023-04-28 19:54 UTC, alanssitis commented on src/amp_local_goal/package.xml
> +  <test_depend>ament_flake8</test_depend>
delete these two

2023-04-30 06:45 UTC, Reschivon commented
Will do a read over of this soon

2023-05-03 20:33 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        super().__init__('CostMap_Subscriber')
```suggestion
        super().__init__('costmap_subscriber')
```
Bit nitpicky, but ROS convention is to keep node names in snake case. Might also consider renaming it to something more descriptive like `find_local_goal`

2023-05-03 20:51 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        max_loc = cv2.minMaxLoc(distImgNormalized)[3]
Would suggest merging the `max_loc` scaling and translation operations into one of two lines for readability.

Something like this pseudocode:
```python

# third return item is the coordinate of the smallest value
min_loc = cv2.minMaxLoc(distImgNormalized)[3]
min_loc_global_coords = (min_loc[0]  * costmapResolution  + xOffset, min_loc[1]  * costmapResolution  + yOffset)
```

2023-05-03 20:54 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        self.get_logger().info(f"{[centx, centy]}")
```suggestion
        self.get_logger().info(f"Goal pixel coordinates: {[max_loc[0], max_loc[1]]}")
```
Does `centx` exist is `show_costmaps` is False?

2023-05-03 20:56 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        self.get_logger().info(f"{max_loc_costmap_origin_scaled}")
Consider adding labels to your logger messages so it's easy to tell what the numbers mean

2023-05-03 20:57 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        # TODO: FMM planner, scipy
The current algo seems stable so far. We might not need FMM at all

2023-05-03 21:00 UTC, xclucas commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +    def inital_pose_callback(self, msg):
What happens if `initial_pose` isn't received before `costmap_callback` runs? `costmap_callback` should refuse to run and print a WARN log if that happens. I know it's not a problem currently but it might help debugging in the future.

2023-05-03 21:57 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        self.goal_pose_publisher = self.create_publisher(
Is there a reason for needing a timed publisher? Why not just publish whenever a costmap is received?

2023-05-03 21:58 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        msg = PoseStamped()
Some nodes (like rviz) will refuse messages without a proper timestamp. I think default `PoseStamped` sets that to 0 but you can steal the timestamp from the costmap.

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        msg = PoseStamped()
Concur, look here https://navigation.ros.org/configuration/packages/bt-plugins/decorators/GoalUpdater.html

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/package.xml
> +  <maintainer email="adhomne@purdue.edu">adhomne</maintainer>
```suggestion
  <maintainer email="adhomne@purdue.edu">YOUR_NAME</maintainer>
```

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +}
Could we make these parameters so that changing these won't require changes to source? Thoughts @Reschivon ?

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +    rclpy.shutdown()
```suggestion
    rclpy.init(args=args)
    subscriber = CostMapSubscriber()
    rclpy.spin(subscriber)
    subscriber.destroy_node()
    rclpy.shutdown()
```

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/package.xml
> +  <test_depend>python3-pytest</test_depend>
```suggestion
```

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/setup.py
> +    maintainer='adhomne',
Ditto

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/setup.py
> +    tests_require=['pytest'],
No pytests (yet :P)

2023-05-03 22:58 UTC, alanssitis commented on src/amp_local_goal/test/test_pep257.py
This test requires you to thoroughly document your functions and files. Might make you fail CI.

2023-05-03 22:59 UTC, alanssitis commented on src/amp_local_goal/test/test_pep257.py
Narrator: It did.

2023-05-03 23:05 UTC, Reschivon commented on src/amp_local_goal/test/test_pep257.py
ain't nobody got time for that

2023-05-03 23:16 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +}
`COST_IMAGE_MAPPINGS` is for visualization so it can be set wherever. 

The other variables mirror the hardcoded values in section 6 of [costmap_2d](http://wiki.ros.org/costmap_2d). However they don't seem to be used in goal selection at all. The actual critical value is the  `100` around line 80 on `cv2.threshold` and I'd suggest adding a parameter for that @arya1106

2023-05-03 23:31 UTC, alanssitis commented on src/amp_local_goal/test/test_pep257.py
just one line is enough

2023-05-04 22:42 UTC, arya1106 commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +}
Yeah, the mirrored constants are just so we can visualize the different costmap values and know what kind of value we're mapping to a brightness value. Parameter is a good idea, adding that.

2023-05-04 22:43 UTC, arya1106 commented on src/amp_local_goal/test/test_pep257.py
Docstrings and type hints? Or anything more?

2023-05-04 22:51 UTC, arya1106 commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        self.goal_pose_publisher = self.create_publisher(
Mirroring what Xuyang and I talked about in-person: 

Right now, some obstacles are not always detected on the first iteration of the costmap (at least in the simulator) as the kart drives forward, but it's usually caught within 3 updates (3 sec). So if the new goal is published every 3 seconds, you end up skipping the "bad" goals with incomplete costmaps. Of course, there is always the chance that the "bad" goal is on that third iteration, but it's usually not the case. Thoughts on how to proceed?

2023-05-09 15:39 UTC, alanssitis requested changes
one last thing and I'll merge

2023-05-09 15:39 UTC, alanssitis commented on src/amp_local_goal/README.md
> +## Files
run `tree` on directory and add files here

2023-05-10 04:48 UTC, alanssitis submitted a review, later dismissed
Will clean up later, but LGTM

2023-05-10 04:53 UTC, arya1106 commented
I’ve got spotty internet access atm, since I’m in travelling, but I should have a better connection in the next few days, I’ll finish up the readme and move the current plotting code to `meshgrid` instead of `linspace`.

2023-05-10 04:55 UTC, alanssitis commented
No worries, I think we are planning to test it on thursday. Looking forward to get it integrated with the stack!

2023-05-10 07:58 UTC, Reschivon commented
Yeah its good and the `meshgrid` is not necessary unless you want to

2023-05-12 07:28 UTC, Reschivon commented
@arya1106 Added readme for you

2023-05-12 07:28 UTC, Reschivon approved these changes
lgtm, long overdue @arya1106 you can hit merge yourself

2023-05-12 07:29 UTC, Reschivon commented on src/amp_local_goal/amp_local_goal/follow_waypoint.py
> +        self.goal_pose_publisher = self.create_publisher(
Not that important, resolving in favor of getting this merged

2023-05-12 07:58 UTC, merged