RANSAC Segmentation
Autonomous-Motorsports-Purdue/AMP_ASSv3 pull request #39
Opened 2023-04-29 07:08 UTC by Reschivon

No docs yet, need readme and testing

## Brief Description

TODO hehe

## Related Issues

Closes ...

Opens ...

## Details

## Tasks

- [ ] Finished all sub-tasks (from issues)
- [ ] Updated Documentation
- [ ] Tests written/updated and implemented to CI

2023-04-30 01:20 UTC, alanssitis commented
do we still wanna use ransac since patchwork seems to work somewhat well?

2023-04-30 06:47 UTC, Reschivon commented
looks like ransac is better with the improvements i made to it

2023-04-30 18:14 UTC, alanssitis requested changes
Add it to `kart.launch.py` and update `README`.

2023-04-30 18:14 UTC, alanssitis commented on src/amp_kart_segmentation/src/segmentation.cpp
> +        // }
ditto

2023-04-30 18:14 UTC, alanssitis commented on src/amp_kart_segmentation/src/segmentation.cpp
> +
remove unnecessary code

2023-04-30 19:32 UTC, Reschivon commented
@alanssitis ur precommit is missing a package for some reason

merge this pls

2023-05-11 19:30 UTC, alanssitis commented
Close since #38 merged.

2023-05-11 19:30 UTC, closed without merging