Add tips for running rosbags on WSL
Autonomous-Motorsports-Purdue/AMP_ASSv3 pull request #40
Opened 2023-04-30 19:44 UTC by Reschivon

## Brief Description

No code, just a README file.

## Related Issues

Closes ...

Opens ...

## Details

## Tasks

- [ ] Finished all sub-tasks (from issues)
- [ ] Updated Documentation
- [ ] Tests written/updated and implemented to CI

2023-04-30 19:57 UTC, alanssitis requested changes

2023-04-30 19:57 UTC, alanssitis commented on README.md
> +  Please follow ROS standard naming and project conventions:
They are two different bullet points

2023-04-30 19:57 UTC, alanssitis commented on rosbag_tips.md
markdown file names should be capitalized. Perhaps `WSL_ROSBAG_TIPS.md`

2023-05-03 20:14 UTC, Reschivon commented
@alanssitis can you approve this

2023-05-03 22:46 UTC, alanssitis requested changes
Some minor changes.

2023-05-03 22:46 UTC, alanssitis commented on README.md
> -
Woops I mischaracterized previous thing. It was a sub-header.

2023-05-03 22:46 UTC, alanssitis commented on WSL_ROSBAG_TIPS.md
> +`sudo apt update` 2. Then install the bag compatibility plugin `sudo apt install ros-<distro>-rosbag2-bag-v2-plugins`. This will install its dependency, `ros-distro-ros1-bridge`, which further requir
Numbered entry 2 and 3 fix!

2023-05-12 00:54 UTC, merged